---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appium
  labels:
    app: appium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appium
  template:
    metadata:
      labels:
        app: appium
    spec:
      containers:
      - name: appium
        image: appium/appium:1.9.1-p0
        ports:
        - containerPort: 4723
---
apiVersion: v1
kind: Service
metadata:
  name: appium
spec:
  selector:
    app: appium
  ports:
  - protocol: TCP
    port: 4723
    targetPort: 4723
    nodePort: 30723
  type: NodePort
